import std/num/int32

type reuse3
  Reuse3(a : pad, b : pad, c : pad)

type afew<a>
  One(a : a, b : pad, c : pad)
  Two(a : a, b : a, c : pad)
  Three(a : a, b : a, c : a)

type tuple<a>
  Pair(a : a, b : a, c : pad)
  Triple(a : a, b : a, c : a)

type seq<a>
  Empty
  Unit(a : a, b : pad, c : pad)
  More0(l : a, s : seq<tuple<a>>, r : afew<a>)
  More(l : tuple<a>, s : seq<tuple<a>>, r : afew<a>)

type buffer
  BNil
  BCons(next : buffer, b : pad, c : pad)

value type bseq<a>
  BSeq(s : seq<a>, q : buffer)

// Isomorphic to (a,b,c,d) but unboxed value
value type tuple4<a,b,c,d>
  Tuple4(fst:a, snd:b, thd:c, field4:d)

fun bhead(^bs : bseq<a>) : exn a
  match bs
    BSeq(s, _) -> head(s)

fun head(^s : seq<a>) : exn a
  match s
    Unit(x) -> x
    More0(x, _, _) -> x
    More(Pair(x, _, _), _, _) -> x
    More(Triple(x, _, _), _, _) -> x

fip fun bcons(x : a, u3 : reuse3, bs : bseq<a>) : exn bseq<a>
  match bs
    BSeq(s, b) ->
      val (s', b') = cons(x, u3, s, b)
      BSeq(s', b')

fip fun cons(x : a, u3 : reuse3, s : seq<a>, b : buffer) : exn (seq<a>, buffer)
  match s
    Empty -> (Unit(x, Pad, Pad), b)
    Unit(y, _, _) -> (More0(x, Empty, One(y, Pad, Pad)), b)
    More0(y, q, u) -> (More(Pair(x, y, Pad), q, u), b)
    More(Pair(y, z, _), q, u) -> (More(Triple(x, y, z), q, u), BCons(b, Pad, Pad))
    More(Triple(y, z, w), q, u) ->
      match b
        BCons(b', _, _) ->
          val (q', b'') = cons(Pair(z, w, Pad), u3, q, b')
          (More(Pair(x, y, Pad), q', u), b'')

fip(1) fun buncons(bs : bseq<a>) : exn (a, reuse3, bseq<a>)
  match bs
    BSeq(s, b) ->
      val Tuple4(x, u3, s', b') = uncons(s, b)
      (x, u3, BSeq(s', b'))

fip(1) fun uncons(s : seq<a>, b : buffer) : exn tuple4<a, reuse3, seq<a>, buffer>
  match s
    Unit(x, _, _) -> Tuple4(x, Reuse3(Pad, Pad, Pad), Empty, b)
    More(Triple(x, y, z), q, u) ->
      match b
        BCons(b', _, _) -> Tuple4(x, Reuse3(Pad, Pad, Pad), More(Pair(y, z, Pad), q, u), b')
    More(Pair(x, y, _), q, u) -> Tuple4(x, Reuse3(Pad, Pad, Pad), More0(y, q, u), b)
    More0(x, q, u) ->
      val (q', b') = more0(q, u, b)
      Tuple4(x, Reuse3(Pad, Pad, Pad), q', b')

fip fun more0(q : seq<tuple<a>>, u : afew<a>, b : buffer) : exn (seq<a>, buffer)
  match q
    Empty ->
      match u
        One(x, _, _) -> (Unit(x, Pad, Pad), b)
        Two(y, z, _) -> match b
          BCons(b', _, _) -> (More0(y, Empty, One(z, Pad, Pad)), b')
        Three(y, z, w) -> match b
          BCons(b', _, _) -> (More0(y, Empty, Two(z, w, Pad)), b')
    Unit(p, _, _) ->
      match p
        Pair(x, y, _) -> (More(Pair(x, y, Pad), Empty, u), b)
        Triple(x, y, z) ->
          match b
            BCons(b', _, _) -> (More0(x, Unit(Pair(y, z, Pad), Pad, Pad), u), b')
    More0(p, q1, u1) ->
      match p
        Pair(x, y) ->
          val (q1', b') = more0(q1, u1, b)
          (More(Pair(x, y, Pad), q1', u), b')
        Triple(x, y, z) ->
          match b
            BCons(b', _, _) -> (More0(x, More0(Pair(y, z, Pad), q1, u1), u), b')
    More(Pair(p, y1), q1, u1) ->
      match p
        Pair(x, y) -> (More(Pair(x, y, Pad), More0(y1, q1, u1), u), b)
        Triple(x, y, z) ->
          match b
            BCons(b', _, _) -> (More0(x, More(Pair(Pair(y, z, Pad), y1, Pad), q1, u1), u), b')
    More(Triple(p, y1, z1), q1, u1) ->
      match b
        BCons(b', _, _) ->
          match p
            Pair(x, y) -> (More(Pair(x, y, Pad), More(Pair(y1, z1, Pad), q1, u1), u), b')
            Triple(x, y, z) -> (More0(x, More(Triple(Pair(y, z, Pad), y1, z1), q1, u1), u), b')

fip fun bsnoc(bs : bseq<a>, u3 : reuse3, x : a) : exn bseq<a>
  match bs
    BSeq(s, b) ->
      val (s', b') = snoc(s, b, u3, x)
      BSeq(s', b')

fip fun snoc(s : seq<a>, b : buffer, u3 : reuse3, x : a) : exn (seq<a>, buffer)
  match s
    Empty -> (Unit(x, Pad, Pad), b)
    Unit(y, _, _) -> (More0(y, Empty, One(x, Pad, Pad)), b)
    More0(u, q, One(y, _, _)) -> (More0(u, q, Two(y, x, Pad)), BCons(b, Pad, Pad))
    More0(u, q, Two(y, z, _)) -> (More0(u, q, Three(y, z, x)), BCons(b, Pad, Pad))
    More0(u, q, Three(y, z, w)) ->
      match b
        BCons(b', _, _) ->
          val (q', b'') = snoc(q, b', u3, Pair(y, z, Pad))
          (More0(u, q', Two(w, x, Pad)), b'')
    More(u, q, One(y, _, _)) -> (More(u, q, Two(y, x, Pad)), BCons(b, Pad, Pad))
    More(u, q, Two(y, z, _)) -> (More(u, q, Three(y, z, x)), BCons(b, Pad, Pad))
    More(u, q, Three(y, z, w)) ->
      match b
        BCons(b', _, _) ->
          val (q', b'') = snoc(q, b', u3, Pair(y, z, Pad))
          (More(u, q', Two(w, x, Pad)), b'')

fun main() ()